### ISSUE TITLE
Link on forum header / footer links to page not found

### ISSUE THREAD

**Issue by Badgerbaiter** [marttiphpbb/phpbb-ext-calendar#1]
As  above - I hit the Calendar button and it takes me to the page as seen on the left::
I have the forum installed in child folder to my main website.
Any clues? 
![forum](https://cloud.githubusercontent.com/assets/11996180/7602944/252ccbbc-f923-11e4-8069-8f153294db0e.jpg)

**Comment by marttiphpbb** [comment]
Sorry, this extension is only in the initial stage of development and is far from functional yet. I will put a notice on the README.md

**Comment by Badgerbaiter** [comment]
No worries at all - I suspect it is an issue on my end - I had the exact same issue with a different Calendar extension :/
Much obliged for the work you are putting into it.
