### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by davidcantonnoteges** [marttiphpbb/phpbb-ext-calendar#3]
I installed and enabled the extension,
but when i join to calendar index page, this error appears:

Catchable fatal error: Argument 1 passed to marttiphpbb\calendar\core\event_container::create_event_rows() must be an instance of marttiphpbb\calendar\core\int, string given, called in /usr/home/lclimpresion.com/web/samsungners/ext/marttiphpbb/calendar/controller/main.php on line 178 and defined in /usr/home/lclimpresion.com/web/samsungners/ext/marttiphpbb/calendar/core/event_container.php on line 124

**Comment by marttiphpbb** [comment]
This extension is only in the initial stage of development and is far from functional yet. See the notice in  the README.md

**Comment by Galixte** [comment]
@davidcantonnoteges take a look at this: http://www.steven-clark.online/phpBB3-Extensions/viewtopic.php?f=4&t=60.
