### ISSUE TITLE
General Error.

### ISSUE THREAD

**Issue by deckyon** [marttiphpbb/phpbb-ext-calendar#4]
Using the latest version of phpBB (3.2.1) with a mostly vanilla experience.  I am really needing a working calendar.  I am trying to get this one working, but when I think it is set up, I submit the post and I get the following:

`General Error
SQL ERROR [ mysqli ]

Out of range value for column 'topic_calendar_start' at row 1 [1264]

SQL

UPDATE fotd_topics SET forum_id = 42, icon_id = 0, topic_title = 'Mythics for Mats', topic_first_poster_name = 'Deckyon', topic_type = 0, topic_time_limit = 0, poll_title = '', poll_start = 0, poll_max_options = 0, poll_length = 0, poll_vote_change = 0, topic_last_view_time = 1513106928, topic_attachment = 0, topic_calendar_start = 1513166400, topic_calendar_end = 1513166400 WHERE topic_id = 7

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/includes/functions_posting.php
LINE: 1918
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/posting.php
LINE: 1424
CALL: submit_post()`

**Comment by marttiphpbb** [comment]
This extension is only in the initial stage of development and is far from functional yet. See the notice in the README.md

#3 
#2
