### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by kromonos** [marttiphpbb/phpbb-ext-calendar#5]
Got a php fatal error:
`PHP Fatal error:  Uncaught TypeError: Argument 4 passed to marttiphpbb\\calendarinput\\render\\posting::__construct() must be an instance of marttiphpbb\\calendarinput\\render\\input_settings, instance of marttiphpbb\\calendarinput\\render\\include_assets given, called in /var/customers/webs/kromonos/bless-rollenspiel.de/cache/production/container_4335734bbdd20f586549a504dff5f80c.php on line 2230 and defined in /var/customers/webs/kromonos/bless-rollenspiel.de/ext/marttiphpbb/calendarinput/render/posting.php:40\nStack trace:\n#0 /var/customers/webs/kromonos/bless-rollenspiel.de/cache/production/container_4335734bbdd20f586549a504dff5f80c.php(2230): marttiphpbb\\calendarinput\\render\\posting->__construct(Object(marttiphpbb\\calendarinput\\repository\\settings), Object(phpbb\\template\\twig\\twig), Object(phpbb\\language\\language), Object(marttiphpbb\\calendarinput\\render\\include_assets), Object(marttiphpbb\\calendarinput\\render\\input_settings))\n#1 /var/customers/webs/kromonos/bless-rollenspiel.de/vendor/symfony/dependency-injection/Container.php(297) in /var/customers/webs/kromonos/bless-rollenspiel.de/ext/marttiphpbb/calendarinput/render/posting.php on line 40, referer: https://bless-rollenspiel.de/viewforum.php?f=9`

phpbb Version 3.2.2  
PHP 7.2  
Apache 2.4  

Activated mods:
Auto Drafts 1.1.3  
Board Announcements 1.0.6   
Board Rules 2.1.1   
Delete My Account 1.0.0   
FAQ manager 1.0.0   
Feed post bot 1.0.11    
Friends and foes  1.0.2   
Hide Bots 1.0.2   
Hide Newest User  1.1.0   
Knowledge Base  1.0.2   
Lightbox  1.0.5   
Notes 2.0.0   
Notify Admin on Registration  1.0.1   
Pages 2.0.3   
phpBB 3.2 Auto Ban  1.0.1   
phpBB Media Embed PlugIn  1.0.1   
Post Count Requirements 1.0.0   
Recent Topics 2.2.7   
Simple mentions 1.0.2   
Simple Spoiler  1.2.1   
Stop Forum Spam 1.1.9   
Topic Restriction 1.0.1   
Username History  1.0.0

**Comment by marttiphpbb** [comment]
ah yes, as from the README:
"This extension is only in the stage of initial development"
So you won't get anything useful yet.
