### ISSUE TITLE
Add support for PHP installations with no calendar extension installed

### ISSUE THREAD

**Issue by mentos** [marttiphpbb/phpbb-ext-calendar#9]
@marttiphpbb first things, first: thanks for this useful extension!

I was thinking that it might make sense to add support for PHP installations that haven't the calendar extension installed. Many shared hosting providers don't know or won't install an extension because they don't want to mess with their existing setup. Some PHPBB installations (such as mine) are already installed in suchs hosts and having no native calendar extension support acts as a blocker for people that want to use your extension.

[For a board I maintain](https://www.forgotten-scroll.gr/) I modified the extension code and added [fisharebest/ext-calendar](https://github.com/fisharebest/ext-calendar) as a dependency for both `calendarmonoinput` and `calendarmonthview` and everything seems to work as expected.

What do you think about adding this dependencies + autoloader in your extension? The `fisharebest/ext-calendar` should be loaded only when the native extensions is not found.

**Comment by marttiphpbb** [comment]
That sounds good. Did you have do something apart from adding to composer.json? And does it work then only as a fallback?

**Comment by mentos** [comment]
In my case I didn't went that far to add the fallback, but I believe it should be something easy to do given that we're able to check if an extension is loaded with `extension_loaded( 'calendar' )`. I wanted a quick ~and dirty~ solution for the time being, but it's something I'm planning to add just in case the provider makes any changes to the server.

As for changes in the code, you'll need to bundle the `fisharebest/ext-calendar` under the `vendor` folder in order for the extension to load if needed. This will yield some changes to `.gitignore` and of course `vendor/`.

Thoughts?

**Comment by marttiphpbb** [comment]
Inspecting [fisharebest/ext-calendar](https://github.com/fisharebest/ext-calendar) I think the library will take care of adding the functions when they are not present automatically. So I think I just have to include the library in composer.json and provide a build (with vendor/ included).

**Comment by mentos** [comment]
Indeed, it seems that it does in the `shim.php` file so it should be only a matter of adding the depency and bundle it 👍

**Comment by marttiphpbb** [comment]
fisharebest/ext-calendar is included now in version 0.4.0 . The build can be found under the latest "Release".

**Comment by marttiphpbb** [comment]
After giving it a thought, I think I have to put the fisharebest/ext-calendar as a dedicated separate phpBB extension. Because the Calendar consists of multiple extensions that all require the calendar functions. If all include fisharebest/ext-calendar that is going to raise a `Fatal error: Cannot redeclare (name of function)` This way it will be also much more distinct and less maintance for me.

**Comment by marttiphpbb** [comment]
So the fisharebest/ext-calendar dependancy is going to be removed again and to be put in a dedicated phpBB extension.

**Comment by marttiphpbb** [comment]
Here is the new extension: [PHP Ext Calendar](https://github.com/marttiphpbb/phpbb-ext-phpextcalendar)
